# Generated by Django 2.2.3 on 2019-08-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='Enter a description of this saucer')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of this dish.', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a ingredient', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of this dish.', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Enter the quantity of this dish.', max_digits=10)),
                ('food_saucer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.FoodDish')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Ingredient')),
            ],
        ),
    ]
